name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
        laravel:
          - 6.*
          - 8.*
          - 9.*
        exclude:
          - laravel: 6.*
            php: 8.1

    name: PHP${{ matrix.php }} - L${{ matrix.laravel }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: phpstan

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-progress --no-interaction --no-suggest

      - name: Run PHPStan analysis
        run: vendor/bin/phpstan analyse src config --level 5

      - name: Run PHP-CS-Fixer code-style analysis
        run: vendor/bin/php-cs-fixer fix --dry-run --config=.php_cs
